name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Checkout Bastillion Repository
      uses: actions/checkout@v4
      with:
        repository: lusky3/Bastillion
        path: Bastillion

    - name: Build with Maven
      run: |
        cd Bastillion
        mvn --batch-mode --update-snapshots clean package verify

    - name: Build Docker Image
      run: |
        cd Bastillion
        docker build -t bastillion:latest .

    - name: Get Commit SHA
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker tag bastillion:latest ghcr.io/${{ github.repository_owner }}/bastillion:latest
        docker tag bastillion:latest ghcr.io/${{ github.repository_owner }}/bastillion:${{ steps.vars.outputs.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/bastillion:latest
        docker push ghcr.io/${{ github.repository_owner }}/bastillion:${{ steps.vars.outputs.sha }}

    - name: Maven Dependency Tree Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@v4.1.1